---
version: "3.8"
services:
  scra:
    image: scra:1.0
    build:
      context: .
    environment:
      - MYSQL_SERVER=db_volume
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    networks:
      - db_private
      - scra_net
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops
    networks:
      - db_private
    volumes:
      - db_volume:/var/lib/mysql
    depends_on:
      - scra

networks:
  scra_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.1/16
  db_private:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.5/16
volumes:
  db_volume:

