resources:
- ../../base
namespace: dev
namePrefix: dev-
images:
  - name: anasansarii/scra
    newName: anasansarii/scra
    newTag: latest
labels:
  - pairs:
      version: dev
    includeTemplates: true
replicas:
- name: sra
  count: 5