---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: SRA
  labels:
    version: dev
    app: SRA
  namespace: dev
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: SRA
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: SRA
      labels:
        app: SRA
        version: dev
      namespace: dev
    spec:
      containers:
        - name: SRA
          image: anasansarii/SRA:v1dev
          ports:
            - name: SRAPort
              containerPort: 8080
              protocol: TCP
          env:
            - name: MYSQL_SERVER
              value: db-svc
          livenessProbe:
            httpGet:
              port: 32000
          readinessProbe:
            httpGet:
              port: 32000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
