resources:
- ../../base
namespace: qa
namePrefix: qa-
images:
  - name: anasansarii/scra
    newName: anasansarii/scra
    newTag: qa-latest
labels:
  - pairs:
      version: qa
    includeTemplates: true
replicas:
- name: sra
  count: 3