resources:
- ../../base
namespace: uat
namePrefix: uat-
images:
  - name: anasansarii/SCRA
    newName: anasansarii/SCRA
    newTag: uat-latest
labels:
  - pairs:
      version: uat
    includeTemplates: true
replicas:
- name: SRA
  count: 4